modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory
issueTrackerURL="https://github.com/cybercat5555/BetterAnimals/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-animal-models" #optional
logoFile="logo.png" #optional
credits="Cybercat555 for supplying models and textures for the mobs. its_meow for mod compat and several fixes as well as maintaining and adding new mobs." #optional
authors="Ocelot5836, Cybercat5555, its_meow" #optional
[[mods]] #mandatory
modId="betteranimals" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Cyber's Better Animal Models" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
A mod to improve the vanilla animals' appearance in Minecraft.'''