modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/itsmeow/BetterAnimals/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-animal-models"
logoFile="logo.png"
credits="cybercat555: art, its_meow: programming"
authors="Ocelot5836, cybercat5555, its_meow"

[[mods]]
	modId="betteranimals"
	version="${file.jarVersion}"
	displayName="Cyber's Better Animal Models"
	description='''
	A mod to improve the vanilla animals' appearance in Minecraft.
	'''
	[[dependencies.quark]]
	    modId="quark"
	    mandatory=false
	    ordering="BEFORE"
	    side="CLIENT"
	[[dependencies.midnight]]
	    modId="midnight"
	    mandatory=false
	    ordering="AFTER"
	    side="CLIENT"